

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: skillgro_app
    restart: unless-stopped
    ports:
      - "8080:80"
      
    volumes:
      - ./storage:/var/www/html/storage
      - ./public/uploads:/var/www/html/public/uploads
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=lms_system
      - DB_USERNAME=erzhan
      - DB_PASSWORD=!Gro@2025
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - skillgro_network

  mysql:
    image: mysql:8.0
    container_name: skillgro_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lms_system
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - skillgro_network

  redis:
    image: redis:7-alpine
    container_name: skillgro_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - skillgro_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: skillgro_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: erzhan
      PMA_PASSWORD: !Gro@2025
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 100M
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 300
    volumes:
      - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - skillgro_network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  skillgro_network:
    driver: bridge 